build_from:
  aarch64: public.ecr.aws/g5p5a5k9/optim-on-local-agent-prod:prod
  amd64: public.ecr.aws/g5p5a5k9/optim-on-local-agent-prod:prod
labels:
  org.opencontainers.image.title: "OPTIM-ON"
  org.opencontainers.image.description: "OPTIM-ON energy optimization system by DOMOPTI"
  org.opencontainers.image.vendor: "DOMOPTI S.R.L.S."
  org.opencontainers.image.authors: "DOMOPTI S.R.L.S."
  org.opencontainers.image.url: "https://github.com/DOMOPTI/HA-addons"
  org.opencontainers.image.source: "https://github.com/DOMOPTI/HA-addons"
  org.opencontainers.image.documentation: "https://github.com/DOMOPTI/HA-addons/blob/main/optim-on/README.md"
