name: "OPTIM-ON"
version: "1.0.0"
slug: "optim_on"
description: "OPTIM-ON energy optimization system by DOMOPTI"
url: "https://github.com/DOMOPTI/HA-addons/tree/main/optim-on"
arch:
  - aarch64
  - amd64
init: false
startup: application
boot: auto
ports:
  3000/tcp: 3000
webui: "http://[HOST]:[PORT:3000]"
homeassistant_api: true
image: "ghcr.io/domopti/{arch}-addon-optim-on"
